/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uas;
import javax.swing.JOptionPane;
import Models.user;

/**
 *
 * @author Kenley
 */
public class hal extends javax.swing.JFrame {

    user users = new user();
    
    /**
     * Creates new form 
     */
    public hal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        unama = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        upass = new javax.swing.JLabel();
        btnlogin = new javax.swing.JButton();
        txtpass = new javax.swing.JPasswordField();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        masterbarang = new javax.swing.JMenuItem();
        masteruser = new javax.swing.JMenuItem();
        mastertransaksi = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        unama.setText("username");

        upass.setText("password");

        btnlogin.setText("Login");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });

        menu.setText("Menu");

        masterbarang.setText("Master Barang");
        masterbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masterbarangActionPerformed(evt);
            }
        });
        menu.add(masterbarang);

        masteruser.setText("Master User");
        masteruser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masteruserActionPerformed(evt);
            }
        });
        menu.add(masteruser);

        mastertransaksi.setText("Master Transaksi");
        mastertransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mastertransaksiActionPerformed(evt);
            }
        });
        menu.add(mastertransaksi);

        jMenuBar1.add(menu);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(unama, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(upass)
                                .addGap(37, 37, 37)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnama, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(txtpass)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(btnlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unama)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(upass)
                    .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(btnlogin)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void masterbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masterbarangActionPerformed
        // TODO add your handling code here:
        new barang().setVisible(true);
        new mUser().setVisible(false);
        new transaksi().setVisible(false);
    }//GEN-LAST:event_masterbarangActionPerformed

    private void masteruserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masteruserActionPerformed
        // TODO add your handling code here:
        new mUser().setVisible(true);
        new barang().setVisible(false);
        new transaksi().setVisible(false);
        
    }//GEN-LAST:event_masteruserActionPerformed

    private void mastertransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mastertransaksiActionPerformed
        // TODO add your handling code here:
        new transaksi().setVisible(true);
        new barang().setVisible(false);
        new mUser().setVisible(false);
    }//GEN-LAST:event_mastertransaksiActionPerformed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        // TODO add your handling code here:
        String uname = txtnama.getText();
        String paswd = String.valueOf(txtpass.getPassword());
        int count = users.checkUser(uname,paswd);
        if(count == 0){
            JOptionPane.showMessageDialog(null,"User tidak ditemukan");
        }
        else{
            masterbarang.setEnabled(true);
            masteruser.setVisible(true);
            mastertransaksi.setVisible(true);
            jMenu2.setEnabled(true);
            unama.setVisible(false);
            txtnama.setVisible(false);
            txtpass.setVisible(false);
            upass.setVisible(false);
            btnlogin.setVisible(false);
        }
    }//GEN-LAST:event_btnloginActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new hal().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogin;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem masterbarang;
    private javax.swing.JMenuItem mastertransaksi;
    private javax.swing.JMenuItem masteruser;
    private javax.swing.JMenu menu;
    private javax.swing.JTextField txtnama;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JLabel unama;
    private javax.swing.JLabel upass;
    // End of variables declaration//GEN-END:variables
}
